= dotfiles
:toc:

== Intro

=== Description

Contains `dotfile` configurations and scripts, used to setup my local base dev env.

[NOTE]
This setup is tailored to my own needs, so use at your own risk.

=== Prerequisites

* MacOS
* link:https://brew.sh/[Home brew]

== Get started

* Git clone this repo and `cd` into it
[source,bash]
----
git clone git@github.com:polster/dotfiles.git $HOME/dotfiles
----
* Run the following commands:
[source,bash]
----
# Install packages
brew bundle

# Install oh-my-zsh
make package-install-zsh

# Install sdkman
make package-install-sdkman

# Install dotfiles
make dotfiles-install
----

== Base dev env

Checkout the following instructions, depending on your needs:

* link:docs/java_base_env.adoc[Java base env]

== Hints

=== Command line tools

Starting from scratch, or even after a MacOS version upgrade, it may happen that tools like `git` require installing the `command line tools`. This to be done easily with the following command:

[source,bash]
----
xcode-select --install
----

=== VSCode extensions

To manage extensions in `VSCode`, the following commands are available:
[source,bash]
----
# Install extensions
make vscode-extensions-install

# Dump from existing setup
make vscode-extensions-dump
----

=== Switching between apps like on Windows

For those folks missing the way how to `ALT-Tab` between applications like on Windows, there is a tool for that :-)

Installed automatically with this setup, comes link:https://alt-tab-macos.netlify.app/[alt-tab]. Once started, just hit `Option+Tab`.

=== Advanced window manager

Especially new people to MacOS are not comfortable with the OS functionality application windows can be arranged and resized. Also here, there is a tool for that: link:https://rectangleapp.com/[rectangle]

Installed automatically with this setup, check their user documentation how to use it in detail.